config/routes.rb
Rails.application.routes.draw do
  root 'calendar_events#index'
  devise_for :users
  resources :calendar_events

end

app/models/calendar_event.rb
class CalendarEvent < ActiveRecord::Base
  belongs_to :user
  validates :title, :date, :repeat, presence: true
  validates :repeat, inclusion: { in: %w(once daily weekly monthly yearly) }

  default_scope { order('date::time') }

  def self.all_events_for(date)
    where('date <= ?', "#{date.end_of_day}").select do |calendar_event|
      event_type = "#{calendar_event.repeat.camelize}Event".constantize
      calendar_event.becomes(event_type).check? date
    end
  end
end

app/models/daily_event.rb
class DailyEvent < CalendarEvent
  def check?(date)
    true
  end
end

app/models/monthly_event.rb
class MonthlyEvent < CalendarEvent
  def check?(date)
    self.date.strftime('%d') == date.strftime('%d')
  end
end

app/models/once_event.rb
class OnceEvent < CalendarEvent
  def check?(date)
    self.date.between? date.beginning_of_day, date.end_of_day
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :calendar_events

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def to_s
    fullname.empty? ? email : fullname
  end
end

app/models/weekly_event.rb
class WeeklyEvent < CalendarEvent
  def check?(date)
    self.date.strftime('%w') == date.strftime('%w')
  end
end

app/models/yearly_event.rb
class YearlyEvent < CalendarEvent
  def check?(date)
    self.date.strftime('%d%m') == date.strftime('%d%m')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :fullname
    devise_parameter_sanitizer.for(:account_update) << :fullname
  end
end

app/controllers/calendar_events_controller.rb
class CalendarEventsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_calendar_event, only: [:edit, :update]
  before_action :check_permission, only: [:edit, :update]

  def index
    @events_date =
      if params[:for_date]
        Date.parse(params[:for_date])
      else
        Time.now.in_time_zone('UTC')
      end
    @calendar_events = CalendarEvent.all_events_for @events_date
  end

  def new
    @calendar_event = CalendarEvent.new
  end

  def create
    @calendar_event = CalendarEvent.new(calendar_event_params)
    @calendar_event.user = current_user
    if @calendar_event.save
      flash[:notice] = 'You successfully create new event'
      redirect_to calendar_events_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @calendar_event.update(calendar_event_params)
      flash[:notice] = 'You successfully edit event'
      redirect_to calendar_events_path
    else
      render :edit
    end
  end

  private

  def calendar_event_params
    params.require(:calendar_event).permit(:title, :date, :repeat)
  end

  def find_calendar_event
    @calendar_event = CalendarEvent.find(params[:id])
  end

  def check_permission
    unless @calendar_event.user == current_user
      redirect_to root_path, alert: 'Permission denied'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_events_helper.rb
module CalendarEventsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = "The form contain #{pluralize(resource.errors.count, 'error')}:"

    html = <<-HTML
    <div class="row">
      <div class="col-sm-offset-2 col-sm-4">
        <div id="error_explanation">
          <div class="alert alert-danger">
            #{sentence}
            <ul>
              #{messages}
            </ul>
          </div>
        </div>
      </div>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    resource.errors.empty? ? false : true
  end
end

app/views/calendar_events/_calendar_event.html.slim
h4.user_event class=(calendar_event.user == current_user ? "owner" : "not_owner")
  span.label.label-primary
    = calendar_event.date.strftime("%H:%M")
  em
    small<
      | (by #{calendar_event.user.to_s})

  - if calendar_event.user == current_user
    =< link_to calendar_event.title, edit_calendar_event_path(calendar_event)
  - else
    =< calendar_event.title

  - if calendar_event.repeat != 'once'
    small< This is #{calendar_event.repeat} event. Started at #{calendar_event.date.strftime("%d %B %Y")}

app/views/calendar_events/_calendar_event_form.html.slim
= form_for @calendar_event, html: { class: "form-horizontal" } do |f|

  .row
    .col-sm-offset-2.col-sm-4
      = render 'shared/error_messages', object: f.object

  .form-group
    = f.label :title, class: "col-sm-2 control-label"
    .col-sm-4
      = f.text_field :title, autofocus: true, class: "form-control", placeholder: "Event title..."

  .form-group
    = f.label :date, class: "col-sm-2 control-label"
    .col-sm-4
      = f.datetime_select :date, class: "form-control"

  .form-group
    .col-sm-offset-2.col-sm-4
      => f.radio_button :repeat, 'once', checked: true
      = f.label :repeat_once, 'once'
      =<> f.radio_button :repeat, 'daily'
      = f.label :repeat_daily, 'daily'
      =<> f.radio_button :repeat, 'weekly'
      = f.label :repeat_weekly, 'weekly'
      =<> f.radio_button :repeat, 'monthly'
      = f.label :repeat_monthly, 'monthly'
      =<> f.radio_button :repeat, 'yearly'
      = f.label :repeat_yearly, 'yearly'

  .form-group
    .col-sm-offset-2.col-sm-4
      = f.submit "Save", class: "btn btn-default"

app/views/calendar_events/edit.html.slim
.row
  .col-sm-offset-2.col-sm-4
    h2 Edit event

= render 'calendar_event_form'

app/views/calendar_events/index.html.slim
= render 'layouts/events_buttons'
h3
  = link_to calendar_events_path(for_date: "#{@events_date - 1.day}") do
    span.glyphicon.glyphicon-chevron-left
  | Event for #{@events_date.strftime("%B, %d")}
  = link_to calendar_events_path(for_date: "#{@events_date + 1.day}") do
    span.glyphicon.glyphicon-chevron-right

em#events_count
- unless @calendar_events.empty?
  = render @calendar_events

app/views/calendar_events/new.html.slim
.row
  .col-sm-offset-2.col-sm-4
    h2 Create new event

= render 'calendar_event_form'

app/views/layouts/_alerts.html.slim
- if flash[:notice]
  .alert.alert-success = notice
- if flash[:alert]
  .alert.alert-danger = alert

app/views/layouts/_events_buttons.html.slim
.btn-group
  button.btn.btn-default.active type="button" id="all_events" All events
  button.btn.btn-default type="button" id="my_events" My events

app/views/layouts/_footer.html.slim
.footer.text-right
  em Create with beautifull #{link_to 'Ruby on Rails', 'http://rubyonrails.org/'} framework.

app/views/layouts/_header.html.slim
.header
  .page-header.text-right
    h1 Simple calendar <small>on Ruby on Rails</small>
  = render 'layouts/navigation'

app/views/layouts/_navigation.html.slim
nav.navbar.navbar-default role="navigation"
  .container-fluid

    .navbar-header
      button.navbar-toggle.collapsed type="button" data-toggle="collapse" data-target="#bs-navbar-collapse"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Calendar', root_path, class: "navbar-brand"

    #bs-navbar-collapse.collapse.navbar-collapse
      ul.nav.navbar-nav
        li
          = link_to 'Home', root_path
        - if user_signed_in?
          li
            = link_to 'Profile', edit_user_registration_path
          li
            = link_to 'New event', new_calendar_event_path
          li
            = link_to 'Log out', destroy_user_session_path, method: :delete
        - else
          li
            = link_to 'Sign in', new_user_session_path
          li
            = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title FsCalendar
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    .container

      = render 'layouts/header'
      = render 'layouts/alerts'
      = yield
      = render 'layouts/footer'

    - if Rails.env.development?
      = debug params

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  #error_explanation
    .alert.alert-danger
      | The form contain #{pluralize(object.errors.count, 'error')}
      ul
        - object.errors.full_messages.each do |error|
          li = error